# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys

import pytest
import torch
from _pytest.mark.structures import Mark, MarkDecorator

import flag_gems

# The KernelGen harness runs pytest in-process with its own ``tests`` package
# (kernelgen/tests) earlier on sys.path than this checkout's ``tests`` package.
# With ``--import-mode=importlib`` pytest does not prepend the checkout root, so
# ``tests`` would resolve to the harness's package and ``from . import
# accuracy_utils`` would fail with ImportError during collection. Re-point the
# ``tests`` package at this file's directory before importing the helpers.
_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

import tests as _tests_pkg  # noqa: E402

if _HERE not in getattr(_tests_pkg, "__path__", []):
    sys.modules.pop("tests", None)
    import tests as _tests_pkg  # noqa: E402

from . import accuracy_utils as utils  # noqa: E402
from . import test_utils as tu  # noqa: E402

# ``_nested_tensor_size`` starts with an underscore, and ``pytest.mark``
# refuses to generate a marker via attribute access for such names. Register it
# directly on the MarkGenerator so ``@pytest.mark._nested_tensor_size`` and
# ``-m _nested_tensor_size`` both work.
setattr(
    pytest.mark,
    "_nested_tensor_size",
    MarkDecorator(Mark("_nested_tensor_size", (), {}, _ispytest=True), _ispytest=True),
)

# aten::_nested_tensor_size(Tensor self) -> Tensor returns the
# (num_tensors, num_dims) int64 sizes metadata tensor of a strided-layout
# nested tensor. torch always creates that metadata on the CPU (even when the
# nested tensor lives on CUDA, see torch.nested.nested_tensor) and the native
# reference reads it with a host pointer, so the output values are exact int64
# and every workload below compares with gems_assert_equal. Only dim 0 may be
# ragged; all other dims must match across components (ragged dims beyond 0 are
# a torch-side restriction, not a candidate property).
#
# num_tensors is kept >= 1: the reference in current torch builds segfaults on
# an empty batch (nested_tensor([])), which is a torch-side limit, not a
# candidate property.
#
# The autogenerated aten::_nested_tensor_size.out overload is not tested:
# current torch builds raise NotImplementedError for it on every backend (no
# NestedTensor* kernel is registered for the .out overload and the composite
# fallback does not cover the nested dispatch keys), so the reference itself
# cannot run it.
_NUM_TENSORS = [1, 8, 256]
_NUM_DIMS = [1, 2, 3, 5]
_COMPONENT_DTYPES = utils.ALL_FLOAT_DTYPES + utils.ALL_INT_DTYPES + utils.BOOL_TYPES


def _value_range_layouts():
    """(num_tensors, num_dims) layouts for the value-range sweep."""
    if tu.LEVEL == "quick":
        return [(8, 2)]
    if tu.LEVEL == "all":
        return [(8, 2), (64, 3), (256, 3)]


def _make_input(num_tensors, num_dims, dtype, value_range, seed=0):
    """Deterministic strided-layout nested tensor of ``num_tensors`` rank
    ``num_dims`` components on the test device.

    Dim 0 is ragged (each component has a length in [1, 8]); every other dim is
    fixed at 4. Component values are drawn from ``value_range`` through the
    shared value-range helper (tu.make_input), which snaps the range to the
    representable set per dtype. The operator never reads the values, but the
    component dtype is varied so the candidate must accept every storage dtype
    the nested-tensor runtime supports.
    """
    gen = torch.Generator("cpu").manual_seed(seed)
    lengths = torch.randint(1, 9, (num_tensors,), generator=gen).tolist()
    components = [
        tu.make_input(dtype, (length,) + (4,) * (num_dims - 1), value_range)
        for length in lengths
    ]
    return torch.nested.nested_tensor(components, device=flag_gems.device)


def _resolve_gems_op():
    # Resolved inside each test (never at module import time) so the
    # process-local override injected by KernelGen for this run wins. The
    # default stays None until flag_gems._nested_tensor_size is registered;
    # resolution order is: (1) override, (2) the direct flag_gems callable,
    # (3) LookupError.
    return flag_gems.testing.resolve_gems_op(
        "_nested_tensor_size",
        getattr(flag_gems, "_nested_tensor_size", None),
    )


def _assert_sizes(res_out, ref_out, num_tensors, num_dims):
    # The sizes metadata is always a CPU int64 tensor of shape
    # (num_tensors, num_dims) and its values are exact.
    assert isinstance(res_out, torch.Tensor)
    assert isinstance(ref_out, torch.Tensor)
    assert res_out.dtype == torch.int64
    assert ref_out.dtype == torch.int64
    assert res_out.shape == (num_tensors, num_dims)
    assert ref_out.shape == (num_tensors, num_dims)
    utils.gems_assert_equal(res_out, ref_out)
    # Sizes are non-negative extents.
    assert bool(torch.all(res_out >= 0))


@pytest.mark._nested_tensor_size
@pytest.mark.parametrize("num_tensors", _NUM_TENSORS)
@pytest.mark.parametrize("num_dims", _NUM_DIMS)
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_size(num_tensors, num_dims, dtype):
    # Layout coverage with component values from [-1, 1]: negative and positive
    # values for every storage dtype (bool/int snap the range to the
    # representable set). The reported sizes depend only on component shapes,
    # so column 0 holds the ragged dim-0 lengths and every other column the
    # fixed component extent (4).
    inp = _make_input(num_tensors, num_dims, dtype, ["-1", "1"])
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_size(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_sizes(res_out, ref_out, num_tensors, num_dims)
    gen = torch.Generator("cpu").manual_seed(0)
    lengths = torch.randint(1, 9, (num_tensors,), generator=gen).tolist()
    assert bool(torch.all(res_out[:, 0] == torch.tensor(lengths)))
    if num_dims >= 2:
        assert bool(torch.all(res_out[:, 1:] == 4))


@pytest.mark._nested_tensor_size
@pytest.mark.parametrize("case", _value_range_layouts())
@pytest.mark.parametrize("value_range", tu.selected_ranges())
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_size_value_ranges(case, value_range, dtype):
    # The component values sweep the full spec range set (positive, negative,
    # extreme and degenerate); the reported sizes never change because the
    # operator reads only layout metadata. This proves the candidate accepts
    # every storage dtype and value range the nested-tensor runtime supports.
    num_tensors, num_dims = case
    inp = _make_input(num_tensors, num_dims, dtype, value_range)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_size(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_sizes(res_out, ref_out, num_tensors, num_dims)


@pytest.mark._nested_tensor_size
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_size_uniform(dtype):
    # Every component has the same shape: the nested tensor is not ragged, but
    # _nested_tensor_size must still return the (num_tensors, num_dims) sizes
    # tensor rather than a strided-tensor shape.
    num_tensors, num_dims = 6, 3
    components = [
        tu.make_input(dtype, (4, 4, 4), ["-1", "1"]) for _ in range(num_tensors)
    ]
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    assert inp.is_nested
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_size(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_sizes(res_out, ref_out, num_tensors, num_dims)
    # Every component is (4, 4, 4), so every sizes entry is exactly 4.
    assert bool(torch.all(res_out == 4))


@pytest.mark._nested_tensor_size
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_size_with_empty_components(dtype):
    # Some sub-tensors are empty (dim 0 length 0); their sizes row is (0, 4)
    # and the running batch is still fully described.
    num_tensors, num_dims = 4, 2
    gen = torch.Generator("cpu").manual_seed(1)
    lengths = [
        int(torch.randint(0, 4, (1,), generator=gen).item()) for _ in range(num_tensors)
    ]
    components = [tu.make_input(dtype, (length, 4), ["-1", "1"]) for length in lengths]
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_size(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_sizes(res_out, ref_out, num_tensors, num_dims)
    assert bool(torch.all(res_out[:, 0] == torch.tensor(lengths)))
    assert bool(torch.all(res_out[:, 1] == 4))


@pytest.mark._nested_tensor_size
@pytest.mark.parametrize("dtype", utils.ALL_FLOAT_DTYPES)
def test__nested_tensor_size_nan_inf_values(dtype):
    # nan/inf/-inf/±0.0 component values are ordinary storage: the sizes
    # metadata is derived only from component shapes, so all four entries still
    # report their true extents.
    num_tensors, num_dims = 4, 2
    gen = torch.Generator("cpu").manual_seed(3)
    lengths = torch.randint(1, 5, (num_tensors,), generator=gen).tolist()
    components = []
    for length in lengths:
        values = tu.make_input(dtype, (length, 4), ["-1", "1"])
        values[0, 0] = float("nan")
        values[0, 1] = float("inf")
        values[-1, -1] = float("-inf")
        components.append(values)
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_size(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_sizes(res_out, ref_out, num_tensors, num_dims)


@pytest.mark._nested_tensor_size
def test__nested_tensor_size_dense_raises():
    # _nested_tensor_size dispatches only on NestedTensor* backends; a strided
    # dense tensor has no implementation and raises NotImplementedError. The
    # candidate must fail too rather than silently reporting a bogus sizes row.
    inp = tu.make_input(torch.float32, (4, 4), ["-1", "1"])
    with pytest.raises(NotImplementedError):
        torch.ops.aten._nested_tensor_size(utils.to_reference(inp))
    with pytest.raises((NotImplementedError, RuntimeError, TypeError)):
        _resolve_gems_op()(inp)


@pytest.mark._nested_tensor_size
def test__nested_tensor_size_rejects_non_tensor():
    # The aten schema requires a Tensor; a Python scalar hits the invalid
    # combination of arguments path and raises.
    with pytest.raises(RuntimeError):
        torch.ops.aten._nested_tensor_size(3.14)
    with pytest.raises((TypeError, ValueError, RuntimeError)):
        _resolve_gems_op()(3.14)
