# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import pytest
import torch
from _pytest.mark.structures import Mark, MarkDecorator

import flag_gems

from . import accuracy_utils as utils
from . import test_utils as tu

# ``_nested_tensor_storage_offsets`` starts with an underscore, and ``pytest.mark``
# refuses to generate a marker via attribute access for such names. Register it
# directly on the MarkGenerator so ``@pytest.mark._nested_tensor_storage_offsets``
# and ``-m _nested_tensor_storage_offsets`` both work.
setattr(
    pytest.mark,
    "_nested_tensor_storage_offsets",
    MarkDecorator(
        Mark("_nested_tensor_storage_offsets", (), {}, _ispytest=True),
        _ispytest=True,
    ),
)

# aten::_nested_tensor_storage_offsets(Tensor self) -> Tensor returns the 1-D
# int64 storage-offset metadata of a strided-layout nested tensor:
# offsets[i] is the index, in the flat storage buffer, of the first element of
# sub-tensor i. torch always creates that metadata on the CPU (even when the
# nested tensor lives on CUDA, see torch.nested.nested_tensor) and the native
# reference reads it with a host pointer, so the output values are exact int64
# and every workload below compares with gems_assert_equal. Raggedness beyond
# dim 0 is not a torch restriction -- nested_tensor([zeros(2, 3), zeros(2, 4)])
# builds a strided nested tensor and the op returns the correct offsets -- so
# the sweep below simply holds every dim past 0 fixed to keep the layouts
# readable; test__nested_tensor_storage_offsets_ragged_non_zero_dim covers a
# ragged last dim.
#
# num_tensors = 0 is included: an empty batch (nested_tensor([])) builds a
# well-defined strided nested tensor and the op returns an empty int64 tensor.
#
# Only strided layout is exercised: the reference raises NotImplementedError
# for jagged-layout nested tensors, and the autogenerated
# aten::_nested_tensor_storage_offsets.out overload is not registered for any
# NestedTensor* backend in this build (verified with
# ``torch.ops.aten._nested_tensor_storage_offsets.out(...)``), so neither case
# is a candidate property.
#
# Regular-operator spec coverage notes: this is a unary metadata op, so the
# "shape levels" dimension maps to (num_tensors, num_dims) batch layouts
# instead of the dense POINTWISE_SHAPES, and broadcast (unary op) and backward
# (int64 metadata, no autograd support) do not apply. The op never reads the
# stored values, yet the value-range and nan/inf workloads below still build
# components through the shared tests/test_utils.py helpers so a candidate that
# wrongly derives offsets from the stored values is caught. The negative case
# (plain non-nested tensor) must raise on both the reference and the candidate.
_NUM_TENSORS = [0, 1, 8, 256]
_NUM_DIMS = [1, 2, 3, 5]
_DEFAULT_VALUE_RANGE = ["-1", "1"]


def _can_represent_inf(dtype):
    """True when ``dtype`` can hold +inf (float8_e4m3fn cannot).

    The check performs the same scalar store the nan/inf workload does, because
    constructing a float8_e4m3fn ``inf`` tensor does not raise but silently
    overflows (and float8 casts do not implement isinf).
    """
    try:
        probe = torch.zeros(1, dtype=dtype, device=flag_gems.device)
        probe[0] = float("inf")
    except (RuntimeError, ValueError, TypeError):
        return False
    return bool(torch.isinf(probe.float()).item())


def _nested_dtype_supported(dtype):
    """Probe whether a strided nested tensor of components of ``dtype`` can be
    built on the test device and fed to the reference operator."""
    try:
        low = tu.make_input(dtype, (2, 2), ["0", "1"])
        high = tu.make_input(dtype, (3, 2), ["0", "1"])
        inp = torch.nested.nested_tensor([low, high], device=flag_gems.device)
        torch.ops.aten._nested_tensor_storage_offsets(inp)
    except Exception:
        return False
    return True


# Spec dtype coverage: the required 9 dtypes (int8/uint8/fp8 included) plus the
# extra float/int/bool dtypes FlagGems tests use, deduplicated and then probed
# so a backend that rejects a component dtype is skipped instead of failing.
_DTYPE_CANDIDATES = list(
    dict.fromkeys(
        tu.REQUIRED_DTYPES
        + utils.ALL_FLOAT_DTYPES
        + utils.ALL_INT_DTYPES
        + utils.BOOL_TYPES
    )
)
# Fallback keeps the full candidate list rather than a float32-only one, so a
# failed/absent nested-dtype probe never silently drops the spec-required
# int8/uint8/fp8 dtypes.
_COMPONENT_DTYPES = [
    dtype for dtype in _DTYPE_CANDIDATES if _nested_dtype_supported(dtype)
] or list(_DTYPE_CANDIDATES)
# nan/inf are only representable by some floating dtypes (float8_e4m3fn has no
# inf), so the nan/inf workload is restricted to the ones that can hold them.
_NAN_INF_DTYPES = [
    dtype
    for dtype in _COMPONENT_DTYPES
    if dtype.is_floating_point and _can_represent_inf(dtype)
]


def _make_input(num_tensors, num_dims, dtype, seed=0, value_range=_DEFAULT_VALUE_RANGE):
    """Deterministic strided-layout nested tensor of ``num_tensors`` rank
    ``num_dims`` components on the test device.

    Dim 0 is ragged (each component has a length in [1, 8]); every other dim is
    fixed at 4. The values are never read by the operator, but the component
    dtype is varied so the candidate must accept every storage dtype the
    nested-tensor runtime supports. Components are built with the shared
    value-range helper per the regular-operator spec.
    """
    gen = torch.Generator("cpu").manual_seed(seed)
    lengths = torch.randint(1, 9, (num_tensors,), generator=gen).tolist()
    components = [
        tu.make_input(dtype, (length,) + (4,) * (num_dims - 1), value_range)
        for length in lengths
    ]
    return torch.nested.nested_tensor(components, device=flag_gems.device)


def _make_strided_view_input(dtype, device=None):
    """Strided-layout nested tensor whose storage offsets have gaps.

    Built with aten::_nested_view_from_buffer (a view, so no copy) so the
    per-sub-tensor storage offsets metadata is exactly ``[0, 12, 30, 36]``
    rather than the packed contiguous offsets ``[0, 6, 18, 21]`` that a
    ``nested_tensor(list)`` construction would assign. The buffer values are
    never read by the operator, so any storage dtype is fine. ``device`` lets
    the test build an equivalent view directly on CPU for the TO_CPU reference:
    a non-contiguous nested tensor cannot be moved with ``Tensor.to()``
    ("NestedTensor must be contiguous to get buffer"), which is a torch-side
    limit, not a candidate property.
    """
    if device is None:
        device = flag_gems.device
    # tu.make_input builds on the shared test device; the contiguous buffer
    # can always be moved to ``device``. Its values are never read.
    buf = tu.make_input(dtype, (64,), _DEFAULT_VALUE_RANGE).to(device)
    nested_size = torch.tensor([[2, 3], [4, 3], [1, 3], [3, 3]], dtype=torch.int64)
    nested_strides = torch.tensor([[6, 1], [6, 1], [6, 1], [6, 1]], dtype=torch.int64)
    storage_offsets = torch.tensor([0, 12, 30, 36], dtype=torch.int64)
    return (
        torch.ops.aten._nested_view_from_buffer(
            buf, nested_size, nested_strides, storage_offsets
        ),
        storage_offsets,
    )


def _resolve_gems_op():
    # Resolved inside each test (never at module import time) so the
    # process-local override injected by KernelGen for this run wins. The
    # default stays None until flag_gems._nested_tensor_storage_offsets is
    # registered; resolution order is: (1) override, (2) the direct flag_gems
    # callable, (3) LookupError.
    return flag_gems.testing.resolve_gems_op(
        "_nested_tensor_storage_offsets",
        getattr(flag_gems, "_nested_tensor_storage_offsets", None),
    )


def _assert_offsets(res_out, ref_out, num_tensors):
    # The storage-offsets metadata is always a CPU int64 tensor of shape
    # (num_tensors,) and its values are exact.
    assert isinstance(res_out, torch.Tensor)
    assert isinstance(ref_out, torch.Tensor)
    assert res_out.dtype == torch.int64
    assert ref_out.dtype == torch.int64
    assert res_out.shape == (num_tensors,)
    assert ref_out.shape == (num_tensors,)
    assert res_out.device == ref_out.device
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark._nested_tensor_storage_offsets
@pytest.mark.parametrize("num_tensors", _NUM_TENSORS)
@pytest.mark.parametrize("num_dims", _NUM_DIMS)
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_storage_offsets(num_tensors, num_dims, dtype):
    inp = _make_input(num_tensors, num_dims, dtype)
    ref_inp = utils.to_reference(inp)
    assert ref_inp.is_nested

    ref_out = torch.ops.aten._nested_tensor_storage_offsets(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_offsets(res_out, ref_out, num_tensors)


@pytest.mark._nested_tensor_storage_offsets
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_storage_offsets_ragged_non_zero_dim(dtype):
    # Raggedness is not limited to dim 0: a strided nested tensor whose *last*
    # dim differs between components builds fine and the operator must still
    # return the running element count of the preceding components (here the
    # (2, 3)/(2, 5)/(2, 1)/(2, 4) components pack to 0/6/16/18).
    num_tensors = 4
    components = [
        tu.make_input(dtype, (2, length), _DEFAULT_VALUE_RANGE)
        for length in (3, 5, 1, 4)
    ]
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    assert inp.is_nested
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_storage_offsets(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_offsets(res_out, ref_out, num_tensors)
    utils.gems_assert_equal(res_out, torch.tensor([0, 6, 16, 18], dtype=torch.int64))


@pytest.mark._nested_tensor_storage_offsets
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_storage_offsets_uniform(dtype):
    # Every component has the same shape: the nested tensor is not ragged, but
    # _nested_tensor_storage_offsets must still return one storage offset per
    # sub-tensor rather than collapsing to a strided-tensor result.
    num_tensors = 6
    components = [
        tu.make_input(dtype, (4, 4, 4), _DEFAULT_VALUE_RANGE)
        for _ in range(num_tensors)
    ]
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    assert inp.is_nested
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_storage_offsets(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_offsets(res_out, ref_out, num_tensors)


@pytest.mark._nested_tensor_storage_offsets
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_storage_offsets_with_empty_components(dtype):
    # Some sub-tensors are empty (dim 0 length 0); they consume no storage, so
    # their offsets repeat the previous row and the whole batch is still fully
    # described.
    num_tensors = 4
    gen = torch.Generator("cpu").manual_seed(1)
    components = []
    for _ in range(num_tensors):
        length = int(torch.randint(0, 4, (1,), generator=gen).item())
        components.append(tu.make_input(dtype, (length, 4), _DEFAULT_VALUE_RANGE))
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_storage_offsets(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_offsets(res_out, ref_out, num_tensors)


@pytest.mark._nested_tensor_storage_offsets
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_storage_offsets_non_contiguous(dtype):
    # Storage offsets are metadata, not a function of sizes: when a strided
    # nested tensor is built over a buffer with gaps between sub-tensors, the
    # operator must return the stored offsets (0, 12, 30, 36) rather than the
    # packed contiguous offsets (0, 6, 18, 21).
    inp, storage_offsets = _make_strided_view_input(dtype)
    ref_device = torch.device("cpu") if utils.TO_CPU else flag_gems.device
    ref_inp, _ = _make_strided_view_input(dtype, ref_device)
    assert inp.is_nested
    assert ref_inp.is_nested

    ref_out = torch.ops.aten._nested_tensor_storage_offsets(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_offsets(res_out, ref_out, 4)
    utils.gems_assert_equal(res_out, storage_offsets)


@pytest.mark._nested_tensor_storage_offsets
@pytest.mark.parametrize("value_range", tu.selected_ranges())
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_storage_offsets_value_ranges(dtype, value_range):
    # Regular-operator spec: value-range coverage. The operator never reads the
    # stored values, so the offsets equal the packed contiguous offsets for
    # every range; building the components with the shared value-range helper
    # still catches a candidate that derives offsets from the stored values.
    num_tensors, num_dims = 8, 3
    inp = _make_input(num_tensors, num_dims, dtype, value_range=value_range)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_storage_offsets(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_offsets(res_out, ref_out, num_tensors)


@pytest.mark._nested_tensor_storage_offsets
@pytest.mark.parametrize("dtype", _NAN_INF_DTYPES)
def test__nested_tensor_storage_offsets_nan_inf(dtype):
    # Regular-operator spec: nan/inf coverage. Components containing
    # nan/inf/-inf must not perturb the storage-offset metadata (a candidate
    # that derives offsets from the stored values would produce bogus offsets).
    num_tensors = 4
    gen = torch.Generator("cpu").manual_seed(0)
    lengths = torch.randint(1, 9, (num_tensors,), generator=gen).tolist()
    components = []
    for length in lengths:
        comp = tu.make_input(dtype, (length, 4), _DEFAULT_VALUE_RANGE)
        flat = comp.reshape(-1)
        flat[0] = float("nan")
        if flat.numel() > 1:
            flat[1] = float("inf")
        if flat.numel() > 2:
            flat[2] = float("-inf")
        components.append(comp)
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_storage_offsets(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_offsets(res_out, ref_out, num_tensors)


@pytest.mark._nested_tensor_storage_offsets
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test__nested_tensor_storage_offsets_non_nested_raises(dtype):
    # Negative case: the operator is only registered for NestedTensor*
    # backends, so a plain strided tensor is rejected by the reference and must
    # be rejected by the candidate as well.
    inp = tu.make_input(dtype, (4, 4), _DEFAULT_VALUE_RANGE)
    ref_inp = utils.to_reference(inp)
    with pytest.raises((NotImplementedError, RuntimeError, TypeError, ValueError)):
        torch.ops.aten._nested_tensor_storage_offsets(ref_inp)
    with pytest.raises((NotImplementedError, RuntimeError, TypeError, ValueError)):
        _resolve_gems_op()(inp)
