# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import pytest
import torch
from _pytest.mark.structures import Mark, MarkDecorator

import flag_gems

from . import accuracy_utils as utils
from . import test_utils as tu

# ``_nested_tensor_size`` starts with an underscore, and ``pytest.mark``
# refuses to generate a marker via attribute access for such names. Register it
# directly on the MarkGenerator so ``@pytest.mark._nested_tensor_size`` and
# ``-m _nested_tensor_size`` both work.
setattr(
    pytest.mark,
    "_nested_tensor_size",
    MarkDecorator(Mark("_nested_tensor_size", (), {}, _ispytest=True), _ispytest=True),
)

# aten::_nested_tensor_size(Tensor self) -> Tensor returns the
# (num_tensors, num_dims) int64 sizes metadata tensor of a strided-layout
# nested tensor: row i holds the extents of sub-tensor i. torch always creates
# that metadata on the CPU (even when the nested tensor lives on CUDA, see
# torch.nested.nested_tensor) and the native reference reads it with a host
# pointer, so the output values are exact int64 and every workload below
# compares with gems_assert_equal. Only dim 0 may be ragged; all other dims must
# match across components (ragged dims beyond 0 are a torch-side restriction,
# not a candidate property).
#
# num_tensors is kept >= 1: the reference in current torch builds segfaults on
# an empty batch (nested_tensor([])), which is a torch-side limit, not a
# candidate property.
#
# The autogenerated aten::_nested_tensor_size.out overload is not tested: this
# torch build raises NotImplementedError for it on every backend (no
# NestedTensor* kernel is registered for the .out overload and the composite
# fallback does not cover the nested dispatch keys), so the reference itself
# cannot run it.
#
# Regular-operator spec coverage notes: this is a unary metadata op, so the
# "shape levels" dimension maps onto (num_tensors, num_dims) batch layouts and
# onto the ranks of the shared tu.selected_shapes() set instead of the dense
# POINTWISE_SHAPES, and broadcast (unary op) and backward (int64 metadata, no
# autograd support) do not apply. The op never reads the stored values, yet the
# value-range and nan/inf workloads below still build components through the
# shared tests/test_utils.py helpers so a candidate that wrongly derives sizes
# from the stored values is caught. Dtypes are filtered by a device probe (see
# ``_supported_component_dtypes``) so int8/uint8/fp8 are covered where the
# runtime can actually materialise them. The negative cases (plain non-nested
# tensor, jagged layout, non-tensor argument) must raise on both the reference
# and the candidate.
_NUM_TENSORS = [1, 8, 64]
_VALUE_RANGE = ["-1", "1"]
_TRAILING_EXTENT = 4
_MAX_TRAILING_EXTENT = 4

# Required dtype coverage first (int8/uint8/fp8), then the shared float/int/bool
# sets. The probe below removes duplicates and anything the active device cannot
# store in a strided nested tensor.
_COMPONENT_DTYPE_CANDIDATES = (
    [torch.int8, torch.uint8, torch.float8_e4m3fn, torch.float8_e5m2]
    + list(utils.ALL_FLOAT_DTYPES)
    + list(utils.ALL_INT_DTYPES)
    + list(utils.BOOL_TYPES)
)


def _supported_component_dtypes():
    """Probe which candidate dtypes can be stored in a strided nested tensor
    that ``_nested_tensor_size`` accepts on the active device.

    ``tu.supported_dtypes`` builds a *dense* probe input, which always raises
    NotImplementedError for this op, so the check has to go through a nested
    tensor. Both the direct reference path and the ``utils.to_reference`` path
    (CPU move when ``--ref cpu`` is used) are exercised; any exception marks the
    dtype unsupported. Falls back to the shared float/int/bool sets if the probe
    cannot establish anything, so the file never collects zero cases.
    """
    supported = []
    for dtype in _COMPONENT_DTYPE_CANDIDATES:
        if dtype in supported:
            continue
        try:
            components = [
                tu.make_input(dtype, (2, 4), ["0", "1"]),
                tu.make_input(dtype, (3, 4), ["0", "1"]),
            ]
            inp = torch.nested.nested_tensor(components, device=flag_gems.device)
            ref_inp = utils.to_reference(inp)
            ref = torch.ops.aten._nested_tensor_size(ref_inp)
        except Exception:
            continue
        if (
            torch.is_tensor(ref)
            and ref.dtype == torch.int64
            and tuple(ref.shape) == (2, 2)
        ):
            supported.append(dtype)
    if not supported:
        return (
            list(utils.ALL_FLOAT_DTYPES)
            + list(utils.ALL_INT_DTYPES)
            + list(utils.BOOL_TYPES)
        )
    return supported


_COMPONENT_DTYPES = _supported_component_dtypes()
_FLOAT_COMPONENT_DTYPES = [d for d in _COMPONENT_DTYPES if d.is_floating_point]


def _supports_inf(dtype):
    """Whether ``dtype`` can represent the inf value.

    fp8 e4m3fn has nan but no inf representation: assigning inf raises
    "value cannot be converted to type at::Float8_e4m3fn without overflow",
    so the nan/inf test guards the inf/-inf writes with this probe.
    """
    try:
        probe = torch.tensor(float("inf"), dtype=dtype)
    except Exception:
        return False
    # e4m3fn silently maps inf to nan instead of raising, so check the stored
    # value rather than relying on the conversion to throw.
    return bool(torch.isinf(probe.to(torch.float64)))


def _make_component(dtype, shape, value_range):
    """Value-range helper that survives the unsigned-dtype snapping of the
    shared helper (uint8 cannot represent the ``-1``/``min`` low bound, which
    ``torch.testing.make_tensor`` rejects for a non-degenerate range)."""
    try:
        return tu.make_input(dtype, shape, value_range)
    except RuntimeError:
        dtype_min, dtype_max = tu.dtype_bounds(dtype)
        low = max(int(tu.resolve_bound(value_range[0], dtype)), int(dtype_min))
        high = min(int(tu.resolve_bound(value_range[1], dtype)), int(dtype_max))
        if low == high:
            return torch.full(shape, low, dtype=dtype, device=flag_gems.device)
        return torch.testing.make_tensor(
            shape, dtype=dtype, device=flag_gems.device, low=low, high=high
        )


def _make_nested(
    num_tensors,
    num_dims,
    dtype,
    value_range=_VALUE_RANGE,
    seed=0,
    trailing=_TRAILING_EXTENT,
):
    """Deterministic strided-layout nested tensor of ``num_tensors`` rank
    ``num_dims`` components on the test device.

    Dim 0 is ragged (each component has a length in [1, 8]); every other dim is
    fixed at ``trailing``. Component values are drawn from ``value_range``
    through the shared value-range helper; the operator never reads them, but
    the component dtype is varied so the candidate must accept every storage
    dtype the nested-tensor runtime supports. Returns the nested tensor and the
    per-component dim-0 lengths used for the expected column 0.
    """
    gen = torch.Generator("cpu").manual_seed(seed)
    lengths = torch.randint(1, 9, (num_tensors,), generator=gen).tolist()
    components = [
        _make_component(dtype, (length,) + (trailing,) * (num_dims - 1), value_range)
        for length in lengths
    ]
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    return inp, lengths


def _shape_level_ranks():
    """Component ranks (>= 1) taken from the shared shape levels.

    A rank-0 sparse/0-dim component cannot form a strided nested tensor, so only
    ranks >= 1 are kept; this keeps the same quick/all shape-level selection as
    ``tu.selected_shapes()`` while adapting it to nested-tensor batches.
    """
    ranks = sorted({len(shape) for shape in tu.selected_shapes() if len(shape) >= 1})
    return ranks if ranks else [2]


def _shape_level_cases():
    """The shared shape levels mapped onto nested-tensor component layouts.

    ``(shape, trailing)`` pairs: the trailing dims of each shared shape are
    clamped to ``_MAX_TRAILING_EXTENT`` so the batch stays small — the operator
    only reports extents, so the exact trailing sizes carry no extra signal,
    while the rank of every shared shape level is preserved.
    """
    cases = []
    for shape in tu.selected_shapes():
        if len(shape) < 1:
            continue
        trailing = tuple(min(int(dim), _MAX_TRAILING_EXTENT) for dim in shape[1:])
        cases.append((shape, trailing))
    return cases


def _value_range_layouts():
    """(num_tensors, num_dims) layouts for the value-range sweep."""
    if tu.LEVEL == "quick":
        return [(8, 2)]
    if tu.LEVEL == "all":
        return [(8, 2), (32, 3), (64, 4)]


def _resolve_gems_op():
    # Resolved inside each test (never at module import time) so the
    # process-local override injected by KernelGen for this run wins. The
    # default stays None until flag_gems._nested_tensor_size is registered;
    # resolution order is: (1) override, (2) the direct flag_gems callable,
    # (3) LookupError.
    return flag_gems.testing.resolve_gems_op(
        "_nested_tensor_size",
        getattr(flag_gems, "_nested_tensor_size", None),
    )


def _assert_sizes(res_out, ref_out, num_tensors, num_dims):
    # The sizes metadata is always a CPU int64 tensor of shape
    # (num_tensors, num_dims) and its values are exact.
    assert isinstance(res_out, torch.Tensor)
    assert isinstance(ref_out, torch.Tensor)
    assert res_out.dtype == torch.int64
    assert ref_out.dtype == torch.int64
    assert tuple(res_out.shape) == (num_tensors, num_dims)
    assert tuple(ref_out.shape) == (num_tensors, num_dims)
    if not utils.TO_CPU:
        # torch creates the sizes metadata on the CPU even for a CUDA nested
        # tensor; the candidate must match that placement (gems_assert_equal
        # would otherwise compare across devices).
        assert res_out.device == ref_out.device
    utils.gems_assert_equal(res_out, ref_out)
    # Sizes are non-negative extents.
    assert bool(torch.all(res_out >= 0))


@pytest.mark._nested_tensor_size
@pytest.mark.parametrize("num_tensors", _NUM_TENSORS)
@pytest.mark.parametrize("num_dims", _shape_level_ranks())
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_size(num_tensors, num_dims, dtype):
    # Layout coverage with component values from [-1, 1]: negative and positive
    # values for every storage dtype (bool/int snap the range to the
    # representable set, unsigned dtypes clamp the low bound). The reported
    # sizes depend only on component shapes, so column 0 holds the ragged dim-0
    # lengths and every other column the fixed component extent (4).
    inp, lengths = _make_nested(num_tensors, num_dims, dtype)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_size(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_sizes(res_out, ref_out, num_tensors, num_dims)
    assert bool(torch.all(res_out[:, 0] == torch.tensor(lengths, dtype=torch.int64)))
    if num_dims >= 2:
        assert bool(torch.all(res_out[:, 1:] == _TRAILING_EXTENT))


@pytest.mark._nested_tensor_size
@pytest.mark.parametrize("case", _shape_level_cases())
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_size_shape_levels(case, dtype):
    # The shared shape levels (0-5 dims) mapped onto nested batches: only the
    # dim-0 extent is ragged per component, so the reported num_dims must equal
    # the rank of the shared shape. Rank-0 shapes are excluded (a 0-dim
    # component cannot form a strided nested tensor).
    shape, trailing = case
    num_tensors = 3
    num_dims = len(shape)
    gen = torch.Generator("cpu").manual_seed(0)
    lengths = torch.randint(1, 5, (num_tensors,), generator=gen).tolist()
    components = [
        _make_component(dtype, (length,) + trailing, _VALUE_RANGE) for length in lengths
    ]
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_size(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_sizes(res_out, ref_out, num_tensors, num_dims)
    assert tuple(res_out.shape) == (num_tensors, len(shape))
    assert bool(torch.all(res_out[:, 0] == torch.tensor(lengths, dtype=torch.int64)))


@pytest.mark._nested_tensor_size
@pytest.mark.parametrize("case", _value_range_layouts())
@pytest.mark.parametrize("value_range", tu.selected_ranges())
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_size_value_ranges(case, value_range, dtype):
    # The component values sweep the full spec range set (positive, negative,
    # extreme and degenerate); the reported sizes never change because the
    # operator reads only layout metadata. This proves the candidate accepts
    # every storage dtype and value range the nested-tensor runtime supports.
    num_tensors, num_dims = case
    inp, lengths = _make_nested(num_tensors, num_dims, dtype, value_range=value_range)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_size(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_sizes(res_out, ref_out, num_tensors, num_dims)
    assert bool(torch.all(res_out[:, 0] == torch.tensor(lengths, dtype=torch.int64)))
    if num_dims >= 2:
        assert bool(torch.all(res_out[:, 1:] == _TRAILING_EXTENT))


@pytest.mark._nested_tensor_size
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_size_uniform(dtype):
    # Every component has the same shape: the nested tensor is not ragged, but
    # _nested_tensor_size must still return the (num_tensors, num_dims) sizes
    # tensor rather than a strided-tensor shape.
    num_tensors, num_dims = 6, 3
    components = [
        _make_component(dtype, (4, 4, 4), _VALUE_RANGE) for _ in range(num_tensors)
    ]
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    assert inp.is_nested
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_size(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_sizes(res_out, ref_out, num_tensors, num_dims)
    # Every component is (4, 4, 4), so every sizes entry is exactly 4.
    assert bool(torch.all(res_out == 4))


@pytest.mark._nested_tensor_size
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_size_with_empty_components(dtype):
    # Some sub-tensors are empty (dim 0 length 0); their sizes row is (0, 4)
    # and the running batch is still fully described.
    num_tensors, num_dims = 4, 2
    gen = torch.Generator("cpu").manual_seed(1)
    lengths = [
        int(torch.randint(0, 4, (1,), generator=gen).item()) for _ in range(num_tensors)
    ]
    components = [
        _make_component(dtype, (length, 4), _VALUE_RANGE) for length in lengths
    ]
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_size(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_sizes(res_out, ref_out, num_tensors, num_dims)
    assert bool(torch.all(res_out[:, 0] == torch.tensor(lengths, dtype=torch.int64)))
    assert bool(torch.all(res_out[:, 1] == 4))


@pytest.mark._nested_tensor_size
@pytest.mark.parametrize("dtype", _FLOAT_COMPONENT_DTYPES)
def test__nested_tensor_size_nan_inf_values(dtype):
    # nan/inf/-inf component values are ordinary storage: the sizes metadata is
    # derived only from component shapes, so all entries still report their true
    # extents.
    num_tensors, num_dims = 4, 2
    gen = torch.Generator("cpu").manual_seed(3)
    lengths = torch.randint(1, 5, (num_tensors,), generator=gen).tolist()
    # fp8 e4m3fn has nan but no inf representation (assigning inf overflows),
    # so the inf/-inf writes are guarded; nan is always covered.
    has_inf = _supports_inf(dtype)
    components = []
    for length in lengths:
        values = _make_component(dtype, (length, 4), _VALUE_RANGE)
        values[0, 0] = float("nan")
        values[0, 1] = float("inf") if has_inf else float("nan")
        values[-1, -1] = float("-inf") if has_inf else float("nan")
        components.append(values)
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_size(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_sizes(res_out, ref_out, num_tensors, num_dims)


# A candidate may legitimately surface a "not supported" failure as a
# Python-level error of any of these kinds, so all of them are accepted.
_NEGATIVE_EXC = (
    NotImplementedError,
    RuntimeError,
    TypeError,
    ValueError,
    AttributeError,
    IndexError,
)


@pytest.mark._nested_tensor_size
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test__nested_tensor_size_dense_raises(dtype):
    # _nested_tensor_size dispatches only on NestedTensor* backends; a strided
    # dense tensor has no implementation and raises NotImplementedError. The
    # candidate must fail too rather than silently reporting a bogus sizes row.
    inp = tu.make_input(dtype, (4, 4), _VALUE_RANGE)
    with pytest.raises(NotImplementedError):
        torch.ops.aten._nested_tensor_size(utils.to_reference(inp))
    with pytest.raises(_NEGATIVE_EXC):
        _resolve_gems_op()(inp)


@pytest.mark._nested_tensor_size
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test__nested_tensor_size_jagged_raises(dtype):
    # Negative case: the jagged layout has no _nested_tensor_size kernel (only
    # the strided NestedTensor backends do), so the reference raises
    # NotImplementedError and the candidate must reject it too.
    ref_device = torch.device("cpu") if utils.TO_CPU else flag_gems.device
    offsets = torch.tensor([0, 2, 5, 9], dtype=torch.int64)
    values = tu.make_input(dtype, (9, 2), _VALUE_RANGE)
    inp = torch.nested.nested_tensor_from_jagged(values, offsets.to(flag_gems.device))
    ref_inp = torch.nested.nested_tensor_from_jagged(
        values.to(ref_device), offsets.to(ref_device)
    )
    assert inp.layout == torch.jagged
    assert ref_inp.layout == torch.jagged
    with pytest.raises(NotImplementedError):
        torch.ops.aten._nested_tensor_size(ref_inp)
    with pytest.raises(_NEGATIVE_EXC):
        _resolve_gems_op()(inp)


@pytest.mark._nested_tensor_size
def test__nested_tensor_size_rejects_non_tensor():
    # The aten schema requires a Tensor; a Python scalar hits the invalid
    # combination of arguments path and raises. The candidate must reject it
    # too.
    with pytest.raises(RuntimeError):
        torch.ops.aten._nested_tensor_size(3.14)
    with pytest.raises(_NEGATIVE_EXC):
        _resolve_gems_op()(3.14)
