# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import importlib
import sys
from pathlib import Path

import pytest
import torch
from _pytest.mark.structures import Mark, MarkDecorator

import flag_gems

# The KernelGen ref-vs-ref verify harness (kernelgen.agents.test_writer._verify_files)
# copies this package tree into a temp dir whose name starts with "tw_verify_",
# chdirs into it, and runs pytest in-process with --import-mode=importlib. It
# never puts that temp root on sys.path, so the *benchmark* phase cannot import
# benchmark/conftest.py (`from . import consts` -> "No module named 'benchmark'",
# pytest exitstatus 2) even though this correctness file is fine. Put the temp
# root on sys.path when that harness layout is detected; normal FlagGems runs
# (cwd = the checkout, or any subdirectory of it) never match and are untouched.
if Path.cwd().name.startswith("tw_verify_"):
    _HARNESS_TMP_ROOT = str(Path.cwd())
    if _HARNESS_TMP_ROOT not in sys.path:
        sys.path.insert(0, _HARNESS_TMP_ROOT)

try:
    from . import accuracy_utils as utils
except ImportError:  # pragma: no cover - KernelGen verify harness shadows `tests`
    # The KernelGen test-writer harness verifies these files from a temp
    # checkout whose sys.path can contain an unrelated `tests` package (the
    # kernelgen repo) that shadows the copied FlagGems tests directory. The
    # relative import above then fails even though accuracy_utils.py sits right
    # next to this file, so load it from this file's directory instead.
    _TEST_DIR = str(Path(__file__).resolve().parent)
    _TESTS_PKG = sys.modules.get("tests")
    if _TESTS_PKG is not None and hasattr(_TESTS_PKG, "__path__"):
        if _TEST_DIR not in _TESTS_PKG.__path__:
            _TESTS_PKG.__path__.append(_TEST_DIR)
        utils = importlib.import_module("tests.accuracy_utils")
    else:
        if _TEST_DIR not in sys.path:
            sys.path.insert(0, _TEST_DIR)
        import accuracy_utils as utils

# ``_nested_tensor_storage_offsets`` starts with an underscore, and ``pytest.mark``
# refuses to generate a marker via attribute access for such names. Register it
# directly on the MarkGenerator so ``@pytest.mark._nested_tensor_storage_offsets``
# and ``-m _nested_tensor_storage_offsets`` both work.
setattr(
    pytest.mark,
    "_nested_tensor_storage_offsets",
    MarkDecorator(
        Mark("_nested_tensor_storage_offsets", (), {}, _ispytest=True),
        _ispytest=True,
    ),
)

# aten::_nested_tensor_storage_offsets(Tensor self) -> Tensor returns the 1-D
# int64 storage-offset metadata of a strided-layout nested tensor:
# offsets[i] is the index, in the flat storage buffer, of the first element of
# sub-tensor i. torch always creates that metadata on the CPU (even when the
# nested tensor lives on CUDA, see torch.nested.nested_tensor) and the native
# reference reads it with a host pointer, so the output values are exact int64
# and every workload below compares with gems_assert_equal. Only dim 0 may be
# ragged; all other dims must match across components (ragged dims beyond 0 are
# a torch-side restriction, not a candidate property).
#
# num_tensors is kept >= 1: the reference in current torch builds segfaults on
# an empty batch (nested_tensor([])), which is a torch-side limit, not a
# candidate property.
#
# Only strided layout is exercised: the reference raises NotImplementedError
# for jagged-layout nested tensors, and the autogenerated
# aten::_nested_tensor_storage_offsets.out overload is not registered for any
# NestedTensor* backend in this build, so neither case is a candidate property.
_NUM_TENSORS = [1, 8, 256]
_NUM_DIMS = [1, 2, 3, 5]
_COMPONENT_DTYPES = utils.ALL_FLOAT_DTYPES + utils.ALL_INT_DTYPES + utils.BOOL_TYPES


def _make_input(num_tensors, num_dims, dtype, seed=0):
    """Deterministic strided-layout nested tensor of ``num_tensors`` rank
    ``num_dims`` components on the test device.

    Dim 0 is ragged (each component has a length in [1, 8]); every other dim is
    fixed at 4. The values are never read by the operator, but the component
    dtype is varied so the candidate must accept every storage dtype the
    nested-tensor runtime supports.
    """
    gen = torch.Generator("cpu").manual_seed(seed)
    lengths = torch.randint(1, 9, (num_tensors,), generator=gen).tolist()
    components = []
    for length in lengths:
        size = (length,) + (4,) * (num_dims - 1)
        if dtype.is_floating_point:
            components.append(torch.randn(size, dtype=dtype, generator=gen))
        elif dtype == torch.bool:
            components.append(torch.randint(0, 2, size, dtype=dtype, generator=gen))
        else:
            components.append(torch.randint(-5, 6, size, dtype=dtype, generator=gen))
    return torch.nested.nested_tensor(components, device=flag_gems.device)


def _make_strided_view_input(dtype, seed=0):
    """Strided-layout nested tensor whose storage offsets have gaps.

    Built with aten::_nested_view_from_buffer (a view, so no copy) so the
    per-sub-tensor storage offsets metadata is exactly ``[0, 12, 30, 36]``
    rather than the packed contiguous offsets ``[0, 6, 30, 33]`` that a
    ``nested_tensor(list)`` construction would assign. The buffer values are
    never read by the operator, so any storage dtype is fine.
    """
    gen = torch.Generator("cpu").manual_seed(seed)
    numel = 64
    # The buffer is created on the CPU with the seeded generator and then moved
    # to the test device (a CUDA generator would need the same device argument).
    # Its values are never read by the operator.
    if dtype.is_floating_point:
        buf = torch.randn(numel, dtype=dtype, generator=gen).to(flag_gems.device)
    elif dtype == torch.bool:
        buf = torch.randint(0, 2, (numel,), dtype=dtype, generator=gen).to(
            flag_gems.device
        )
    else:
        buf = torch.randint(-5, 6, (numel,), dtype=dtype, generator=gen).to(
            flag_gems.device
        )
    nested_size = torch.tensor([[2, 3], [4, 3], [1, 3], [3, 3]], dtype=torch.int64)
    nested_strides = torch.tensor([[6, 1], [6, 1], [6, 1], [6, 1]], dtype=torch.int64)
    storage_offsets = torch.tensor([0, 12, 30, 36], dtype=torch.int64)
    return (
        torch.ops.aten._nested_view_from_buffer(
            buf, nested_size, nested_strides, storage_offsets
        ),
        storage_offsets,
    )


def _resolve_gems_op():
    # Resolved inside each test (never at module import time) so the
    # process-local override injected by KernelGen for this run wins. The
    # default stays None until flag_gems._nested_tensor_storage_offsets is
    # registered; resolution order is: (1) override, (2) the direct flag_gems
    # callable, (3) LookupError.
    return flag_gems.testing.resolve_gems_op(
        "_nested_tensor_storage_offsets",
        getattr(flag_gems, "_nested_tensor_storage_offsets", None),
    )


def _assert_offsets(res_out, ref_out, num_tensors):
    # The storage-offsets metadata is always a CPU int64 tensor of shape
    # (num_tensors,) and its values are exact.
    assert isinstance(res_out, torch.Tensor)
    assert isinstance(ref_out, torch.Tensor)
    assert res_out.dtype == torch.int64
    assert ref_out.dtype == torch.int64
    assert res_out.shape == (num_tensors,)
    assert ref_out.shape == (num_tensors,)
    assert res_out.device == ref_out.device
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark._nested_tensor_storage_offsets
@pytest.mark.parametrize("num_tensors", _NUM_TENSORS)
@pytest.mark.parametrize("num_dims", _NUM_DIMS)
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_storage_offsets(num_tensors, num_dims, dtype):
    inp = _make_input(num_tensors, num_dims, dtype)
    ref_inp = utils.to_reference(inp)
    assert ref_inp.is_nested

    ref_out = torch.ops.aten._nested_tensor_storage_offsets(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_offsets(res_out, ref_out, num_tensors)


@pytest.mark._nested_tensor_storage_offsets
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_storage_offsets_uniform(dtype):
    # Every component has the same shape: the nested tensor is not ragged, but
    # _nested_tensor_storage_offsets must still return one storage offset per
    # sub-tensor rather than collapsing to a strided-tensor result.
    num_tensors = 6
    gen = torch.Generator("cpu").manual_seed(0)
    components = []
    for _ in range(num_tensors):
        if dtype.is_floating_point:
            components.append(torch.randn(4, 4, 4, dtype=dtype, generator=gen))
        elif dtype == torch.bool:
            components.append(
                torch.randint(0, 2, (4, 4, 4), dtype=dtype, generator=gen)
            )
        else:
            components.append(
                torch.randint(-5, 6, (4, 4, 4), dtype=dtype, generator=gen)
            )
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    assert inp.is_nested
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_storage_offsets(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_offsets(res_out, ref_out, num_tensors)


@pytest.mark._nested_tensor_storage_offsets
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_storage_offsets_with_empty_components(dtype):
    # Some sub-tensors are empty (dim 0 length 0); they consume no storage, so
    # their offsets repeat the previous row and the whole batch is still fully
    # described.
    num_tensors = 4
    gen = torch.Generator("cpu").manual_seed(1)
    components = []
    for _ in range(num_tensors):
        length = int(torch.randint(0, 4, (1,), generator=gen).item())
        size = (length, 4)
        if dtype.is_floating_point:
            components.append(torch.randn(size, dtype=dtype, generator=gen))
        elif dtype == torch.bool:
            components.append(torch.randint(0, 2, size, dtype=dtype, generator=gen))
        else:
            components.append(torch.randint(-5, 6, size, dtype=dtype, generator=gen))
    inp = torch.nested.nested_tensor(components, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_storage_offsets(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_offsets(res_out, ref_out, num_tensors)


@pytest.mark._nested_tensor_storage_offsets
@pytest.mark.parametrize("dtype", _COMPONENT_DTYPES)
def test__nested_tensor_storage_offsets_non_contiguous(dtype):
    # Storage offsets are metadata, not a function of sizes: when a strided
    # nested tensor is built over a buffer with gaps between sub-tensors, the
    # operator must return the stored offsets (0, 12, 30, 36) rather than the
    # packed contiguous offsets (0, 6, 30, 33).
    inp, storage_offsets = _make_strided_view_input(dtype)
    assert inp.is_nested
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._nested_tensor_storage_offsets(ref_inp)
    res_out = _resolve_gems_op()(inp)

    _assert_offsets(res_out, ref_out, 4)
    utils.gems_assert_equal(res_out, storage_offsets)
